FROM python:3.13-slim AS builder

ENV PYTHONUNBUFFERED=1 \ 
    PYTHONDONTWRITEBYTECODE=1 

RUN pip install poetry && poetry config virtualenvs.in-project true

COPY pyproject.toml poetry.lock /app/
COPY common/ /app/common
COPY discord-bot/ /app/discord-bot

WORKDIR /app
RUN poetry install --extras discord-bot


FROM python:3.13-slim

COPY --from=builder /app /app

WORKDIR /app

ENV PYTHONPATH=/app

CMD [".venv/bin/python", "discord-bot/main.py"]
