[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "slurp-common"
version = "0.0.1"
dependencies = [
    "colorlog",
]

[tool.setuptools.packages.find]
# This tells setuptools to find packages automatically
